### ISSUE TITLE
(Feature Request) Automate brunch toolchain initialization 

### ISSUE THREAD

**Issue by ameyjoshi3068** [sebanc/brunch-toolchain#1]
First of all **Congratulations** for the new great project
Only one request to you is to automate the  initialization which currently can be achieved by running  `start-toolchain` 
because if I am not wrong it can be loaded along with `shell` in crosh

**Comment by sebanc** [comment]
Thanks :)

I would feel a bit bad about forcing stuff in people's .bashrc. Also, start-toolchain is only necessary to build stuff involving python and perl but many brunch-toolchain components work without it.

Overall, I would prefer that people willing to execute start-toolchain automatically run `echo "start-toolchain" > ~/.bashrc` themselves. I will add it to the instructions.

**Comment by ameyjoshi3068** [comment]
👍
